name: Build Tourist Plugin

on:
  push

env:
  PLUGIN_REPO: pot0to/Tourist
  PROJECT_PATH: Tourist
  INTERNAL_NAME: Tourist
  IS_OFFICIAL: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
          unzip latest.zip -d dalamud/
          echo "DALAMUD_HOME=$PWD/dalamud" >> $GITHUB_ENV

      - name: Restore
        run: |
          dotnet restore -r win

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: release
        with:
          files: ${{env.PROJECT_PATH}}/bin/Release/net8-windows/${{env.INTERNAL_NAME}}/*